apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
  namaspace: default
  labels:
    app: nodejs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs-app
        image: "naveenyogi/nodeapp:node"
        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-app
  namaspace: default
spec:
  selector:
    app: nodejs-app
  type: NodePort
  ports:
    - name: http
      targetPort: 3001
      port: 80
