name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # Change this to the branch you want to trigger the pipeline on

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1

      - name: Configure kubectl
        run: |
          kubectl config set-cluster local --server=http://localhost:8080
          kubectl config set-context local --cluster=local
          kubectl config use-context local

      - name: Configure Docker CLI
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
        run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

      - name: Build Docker image
        run: docker build -t nodeapp1 .

      - name: Tag Docker image
        run: docker tag nodeapp1:latest naveenyogi/nodeapp:latest1

      - name: Push Docker image to Docker Hub
        run: docker push naveenyogi/nodeapp:latest1

      - name: Deploy locally using Docker
        run: docker run -d -p 8080:8080 naveenyogi/nodeapp:latest1

      - name: service list
        run: docker ps

      - name: Get Minikube IP
        id: minikube-ip
        run: |
          MINIKUBE_IP=$(minikube ip)
          if [ -z "$MINIKUBE_IP" ]; then
            echo "::set-output name=ip::localhost"
          else
            echo "::set-output name=ip::$MINIKUBE_IP"
          fi
          
      - name: Print Minikube IP
        run: echo "Minikube IP is ${{ steps.minikube-ip.outputs.ip }}"
