name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # Change this to the branch you want to trigger the pipeline on

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Minikube
        uses: medyagh/setup-minikube@master

      - name: Configure Docker CLI
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

      - name: Build Docker image
        run: docker build -t nodeapp1 .

      - name: Tag Docker image
        run: docker tag nodeapp1:latest naveenyogi/nodeapp:latest1

      - name: Push Docker image to Docker Hub
        run: docker push naveenyogi/nodeapp:latest1

      - name: Deploy to Minikube
        run: |
          kubectl apply -f deployment.yaml
